services:
  qos-sse-broker:
    build: ./qos-sse-broker
    image: jspboix/qos-sse-broker:1.0.0
    container_name: qos-sse-broker
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    labels:
      kompose.service.type: "NodePort"

  qos-data-transfer:
    build: ./qos-data-transfer
    image: jspboix/qos-data-transfer:1.0.0
    container_name: qos-data-transfer
    ports:
      - "8081:8081"
    environment:
      - PILLARBOX_QOS_SSE_URI=http://qos-sse-broker:8080/events
      - SPRING_ELASTICSEARCH_URIS=http://elastic:9200
    labels:
      kompose.service.type: "NodePort"

  elastic:
    build: ./elastic-search
    image: jspboix/elasticsearch:1.0.0
    container_name: elastic
    ports:
      - '9200:9200'
      - '9300:9300'
    labels:
      kompose.service.type: "ClusterIp"
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 512m

  grafana:
    build: ./grafana
    image: jspboix/grafana:1.0.0
    container_name: grafana
    ports:
      - '3000:3000'
    labels:
      kompose.service.type: "NodePort"
