services:
  broker:
    build: ./kafka
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - '29092:29092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092

  kafka-rest-api:
    build: ./qos-rest
    container_name: kafka-rest-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=broker:9092
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6397
    depends_on:
      - broker
      - kafka-connect
      - redis

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"

  kafka-connect:
    build: ./kafka-connect
    container_name: kafka-connect
    ports:
      - '8083:8083'
    depends_on:
      - zookeeper
      - broker
      - elasticsearch
    environment:
      CONNECT_REST_PORT: 8083
      CONNECT_BOOTSTRAP_SERVERS: broker:9092
      CONNECT_ZOOKEEPER_CONNECT: zookeeper:2181

  elasticsearch:
    build: ./elastic-search
    container_name: elastic
    ports:
      - '9200:9200'
      - '9300:9300'

  grafana:
    build: ./grafana
    container_name: grafana
    ports:
      - '3000:3000'

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
