services:
  qos-rest-api:
    build: ./qos-rest
    image: jspboix/qos-rest-api:1.0.0
    container_name: qos-rest-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_ELASTICSEARCH_URIS=http://elastic:9200
    labels:
      kompose.service.type: "NodePort"

  elastic:
    build: ./elastic-search
    image: jspboix/elasticsearch:1.0.0
    container_name: elastic
    ports:
      - '9200:9200'
      - '9300:9300'
    labels:
      kompose.service.type: "ClusterIp"

  grafana:
    build: ./grafana
    image: jspboix/grafana:1.0.0
    container_name: grafana
    ports:
      - '3000:3000'
    labels:
      kompose.service.type: "NodePort"
