services:
  qos-rest-api:
    build: ./qos-rest
    container_name: qos-rest-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_ELASTICSEARCH_URIS=http://elastic:9200
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6397
    depends_on:
      elasticsearch:
          condition: service_healthy
      redis:
        condition: service_started

  redis:
    image: redis:7.2.5
    container_name: redis
    ports:
      - "6379:6379"

  elasticsearch:
    build: ./elastic-search
    container_name: elastic
    ports:
      - '9200:9200'
      - '9300:9300'
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:9200 > /dev/null" ]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    build: ./grafana
    container_name: grafana
    ports:
      - '3000:3000'
