{
 "title": "Error Breakdown",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "bu", "label": "Business Unit", "query": "srf, rts, rsi, rtr, swi" },
   {
    "name": "platform",
    "label": "Player Platform",
    "query": "{\n  \"find\": \"terms\",\n  \"field\": \"data.player.platform.keyword\",\n  \"size\": 1000\n}"
   },
   {
    "name": "device",
    "label": "Device",
    "query": "{\n  \"find\": \"terms\",\n  \"field\": \"data.device.type.keyword\",\n  \"size\": 1000\n}"
   }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lates Errors",
     "type": "logs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "event_name:ERROR AND session.media.id:urn\\:${bu}\\:*\nAND session.player.platform:${platform}\nAND session.device.type:${device}",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  { "title": "Error Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Current Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Errors",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "session_id.keyword", "id": "1", "type": "cardinality" }
     ],
     "query": "event_name:ERROR \nAND session.media.id:urn\\:${bu}\\:*\nAND session.player.platform:${platform}\nAND session.device.type:${device}",
     "timeField": "@timestamp"
    },
    {
     "alias": "Stop",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "session_id.keyword", "id": "1", "type": "cardinality" }
     ],
     "query": "event_name:STOP\nAND session.media.id:urn\\:${bu}\\:*\nAND session.player.platform:${platform}\nAND session.device.type:${device}",
     "timeField": "@timestamp"
    },
    {
     "alias": "Playing",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "session_id.keyword", "id": "1", "type": "cardinality" }
     ],
     "query": "NOT (event_name:ERROR OR STOP)\nAND session.media.id:urn\\:${bu}\\:*\nAND session.player.platform:${platform}\nAND session.device.type:${device}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Device Model",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.device.model.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START AND data.player.platform:${platform} AND\ndata.media.id:urn\\:${bu}\\:*  AND data.device.type:${device}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "session.media.id.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "data.name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND data.severity:FATAL\nAND session.media.id:urn\\:${bu}\\:*\nAND session.player.platform:${platform}\nAND session.device.type:${device}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Error Breakdown",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR AND session.player.platform:${platform} AND\nsession.media.id:urn\\:${bu}\\:*  AND session.device.type:${device}",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}