{
 "title": "Event Breakdown",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "platform",
    "label": "Player Platform",
    "query": "{\n  \"find\": \"terms\",\n  \"field\": \"data.player_platform.keyword\",\n  \"size\": 1000\n}"
   },
   {
    "name": "device",
    "label": "Device",
    "query": "{\n  \"find\": \"terms\",\n  \"field\": \"data.device_type.keyword\",\n  \"size\": 1000\n}"
   },
   { "name": "bu", "label": "Business Unit", "query": "srf, rts, rsi, rtr, swi" }
  ]
 },
 "panels": [
  {
   "title": "Event types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "event_name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "NOT event_name:HEARTBEAT\nAND (\n  (data.player_platform:${platform} AND data.media_id:urn\\:${bu}\\:* AND data.device_type:${device})\n  OR \n  (session.player_platform:${platform} AND session.media_id:urn\\:${bu}\\:* AND session.device_type:${device})\n)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Event Timeline",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "event_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(session.player_platform:${platform}\nAND session.media_id:urn\\:${bu}\\:* \nAND session.device_type:${device}) OR \n(data.player_platform:${platform}\nAND data.media_id:urn\\:${bu}\\:* \nAND data.device_type:${device})",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Player Platform Breakdown",
   "type": "piechart",
   "description": "Usage by platform for the selected time range.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.player_platform.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START AND data.player_platform:${platform} AND\ndata.media_id:urn\\:${bu}\\:*  AND data.device_type:${device}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Platform Timeline",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.player_platform.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START AND\n(data.player_platform:${platform}\nAND data.media_id:urn\\:${bu}\\:* \nAND data.device_type:${device})",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}