{
 "title": "Metrics Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "platform",
    "label": "Player Platform",
    "query": "{\n  \"find\": \"terms\",\n  \"field\": \"data.player_platform.keyword\",\n  \"size\": 1000\n}"
   },
   {
    "name": "device",
    "label": "Device",
    "query": "{\n  \"find\": \"terms\",\n  \"field\": \"data.device_type.keyword\",\n  \"size\": 1000\n}"
   },
   { "name": "bu", "label": "Business Unit", "query": "srf, rts, rsi, rtr, swi" },
   { "name": "media_id", "label": "Media Id", "query": "*" }
  ]
 },
 "panels": [
  {
   "title": "Average bitrate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Bitrate",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "data.bitrate", "id": "1", "type": "avg" }
     ],
     "query": "NOT event_name:(START OR ERROR) AND session.player_platform:${platform} AND\nsession.media_id:urn\\:${bu}\\:* AND session.device_type:${device}\nAND\nsession.media_id:${media_id} ",
     "timeField": "@timestamp"
    },
    {
     "alias": "Bandwidth",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "data.bandwidth", "id": "1", "type": "avg" }
     ],
     "query": "NOT event_name:(START OR ERROR) AND session.player_platform:${platform} AND\nsession.media_id:urn\\:${bu}\\:* AND session.device_type:${device}\nAND\nsession.media_id:${media_id} ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Stall Rate",
   "type": "timeseries",
   "description": "Stall rate normalized to duration watched.",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 0 },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Stall Duration Rate",
   "type": "timeseries",
   "description": "Stall duration duration to watched ratio,",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Average Loading time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "DRM",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "data.time_metrics.drm", "id": "1", "type": "avg" }
     ],
     "query": "event_name:START\nAND data.player_platform:${platform} AND\ndata.media_id:urn\\:${bu}\\:* AND data.device_type:${device}\nAND\ndata.media_id:${media_id} ",
     "timeField": "@timestamp"
    },
    {
     "alias": "Media Source",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "data.time_metrics.media_source", "id": "1", "type": "avg" }
     ],
     "query": "event_name:START\nAND data.player_platform:${platform} AND\ndata.media_id:urn\\:${bu}\\:* AND data.device_type:${device}\nAND\ndata.media_id:${media_id} ",
     "timeField": "@timestamp"
    },
    {
     "alias": "Asset",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "data.time_metrics.asset", "id": "1", "type": "avg" }
     ],
     "query": "event_name:START\nAND data.player_platform:${platform} AND\ndata.media_id:urn\\:${bu}\\:* AND data.device_type:${device}\nAND\ndata.media_id:${media_id} ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Stall Duration",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "data.stall_duration", "id": "1", "type": "avg" }
     ],
     "query": "NOT event_name:(START OR ERROR)\nAND session.player_platform:${platform} AND\nsession.media_id:urn\\:${bu}\\:* AND session.device_type:${device}\nAND\nsession.media_id:${media_id} ",
     "timeField": "@timestamp"
    },
    {
     "alias": "Stall Count",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "data.stall_count", "id": "1", "type": "avg" }
     ],
     "query": "NOT event_name:(START OR ERROR)\nAND session.player_platform:${platform} AND\nsession.media_id:urn\\:${bu}\\:* AND session.device_type:${device}\nAND\nsession.media_id:${media_id} ",
     "timeField": "@timestamp"
    },
    {
     "alias": "Buffer Duration",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "data.buffer_duration", "id": "1", "type": "avg" }
     ],
     "query": "NOT event_name:(START OR ERROR)\nAND session.player_platform:${platform} AND\nsession.media_id:urn\\:${bu}\\:* AND session.device_type:${device}\nAND\nsession.media_id:${media_id} ",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}