{
 "title": "Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "platform",
    "label": "Player Platform",
    "query": "{\n  \"find\": \"terms\",\n  \"field\": \"data.player_platform.keyword\",\n  \"size\": 1000\n}"
   },
   {
    "name": "device",
    "label": "Device",
    "query": "{\n  \"find\": \"terms\",\n  \"field\": \"data.device_type.keyword\",\n  \"size\": 1000\n}"
   },
   { "name": "bu", "label": "Business Unit", "query": "srf, rts, rsi, rtr, swi" }
  ]
 },
 "panels": [
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Event types",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "event_name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "NOT event_name:HEARTBEAT\nAND (\n  (data.player_platform:${platform} AND data.media_id:urn\\:${bu}\\:* AND data.device_type:${device})\n  OR \n  (session.player_platform:${platform} AND session.media_id:urn\\:${bu}\\:* AND session.device_type:${device})\n)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 1 },
   "targets": [
    {
     "alias": "Error",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR\nAND session.player_platform:${platform}\nAND session.media_id:urn\\:${bu}\\:*  AND session.device_type:${device}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Heartbeat",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "alias": "Heartbeats",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:HEARTBEAT AND session.media_id:urn\\:${bu}\\:* AND\nsession.player_platform:${platform}  AND session.device_type:${device}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Buffer",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "Buffer",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:BUFFER\nAND session.player_platform:${platform}\nAND session.media_id:urn\\:${bu}\\:*  AND session.device_type:${device}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Starts",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "alias": "Starts",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START\nAND data.player_platform:${platform}\nAND data.media_id:urn\\:${bu}\\:*  AND data.device_type:${device}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Stalls",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "alias": "Stalls",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:STALL\nAND session.player_platform:${platform}\nAND session.media_id:urn\\:${bu}\\:*  AND session.device_type:${device}",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Average bitrate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "alias": "Bitrate",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "data.bitrate", "id": "1", "type": "avg" }
     ],
     "query": "(NOT event_name:START) AND session.player_platform:${platform} AND\nsession.media_id:urn\\:${bu}\\:*  AND session.device_type:${device}",
     "timeField": "@timestamp"
    },
    {
     "alias": "Bandwidth",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "data.bandwidth", "id": "1", "type": "avg" }
     ],
     "query": "NOT event_name:START AND session.player_platform:${platform} AND\nsession.media_id:urn\\:${bu}\\:*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Average Loading time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "alias": "DRM",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "data.time_metrics.drm", "id": "1", "type": "avg" }
     ],
     "query": "event_name:START AND data.player_platform:${platform}  AND data.device_type:${device}",
     "timeField": "@timestamp"
    },
    {
     "alias": "Media Source",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "data.time_metrics.media_source", "id": "1", "type": "avg" }
     ],
     "query": "event_name:START AND data.player_platform:${platform}",
     "timeField": "@timestamp"
    },
    {
     "alias": "Asset",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "data.time_metrics.asset", "id": "1", "type": "avg" }
     ],
     "query": "event_name:START AND data.player_platform:${platform}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Average Stall Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "alias": "stalls",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "data.stall_count", "id": "1", "type": "avg" }
     ],
     "query": "(NOT event_name:START) AND session.player_platform:${platform} AND\nsession.media_id:urn\\:${bu}\\:* AND session.device_type:${device}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Error Breakdown",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR AND session.player_platform:${platform} AND\nsession.media_id:urn\\:${bu}\\:*  AND session.device_type:${device}",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Browsers",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.browser.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START AND data.player_platform:${platform} AND\ndata.media_id:urn\\:${bu}\\:*  AND data.device_type:${device}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Device Model",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.device_model.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START AND data.player_platform:${platform} AND\ndata.media_id:urn\\:${bu}\\:*  AND data.device_type:${device}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Operating System",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.os_name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:START AND data.player_platform:${platform} AND\ndata.media_id:urn\\:${bu}\\:*  AND data.device_type:${device}",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}