{
 "title": "Player Quality of Service",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "platform",
    "query": "{\n  \"find\": \"terms\",\n  \"field\": \"data.player_platform.keyword\",\n  \"size\": 1000\n}"
   }
  ]
 },
 "panels": [
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Event types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "event_name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.player_platform:${platform} OR session.player_platform:${platform}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Error tracking",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 1 },
   "targets": [
    {
     "alias": "Error",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:ERROR AND session.player_platform:${platform}",
     "timeField": "@timestamp"
    },
    {
     "alias": "Sucess",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_name:END AND session.player_platform:${platform}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Events per second",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Average bitrate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "alias": "Bitrate",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "data.bitrate", "id": "1", "type": "avg" }
     ],
     "query": "(NOT event_name:SESSION) AND session.player_platform:${platform}",
     "timeField": "@timestamp"
    },
    {
     "alias": "Bandwidth",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "data.bandwidth", "id": "1", "type": "avg" }
     ],
     "query": "NOT event_name:SESSION AND session.player_platform:${platform}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Average Loading time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "alias": "DRM",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "data.time_metrics.drm", "id": "1", "type": "avg" }
     ],
     "query": "event_name:SESSION AND data.player_platform:${platform}",
     "timeField": "@timestamp"
    },
    {
     "alias": "Media Source",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "data.time_metrics.media_source", "id": "1", "type": "avg" }
     ],
     "query": "event_name:SESSION AND data.player_platform:${platform}",
     "timeField": "@timestamp"
    },
    {
     "alias": "Asset",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "10s", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "data.time_metrics.asset", "id": "1", "type": "avg" }
     ],
     "query": "event_name:SESSION AND data.player_platform:${platform}",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}