{
 "title": "Session Breakdown",
 "time": { "from": "2024-07-12T13:20:45.445Z", "to": "2024-07-12T13:33:49.807Z" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "session_id",
    "label": "Session",
    "query": "b18f63aa-b3aa-49b5-9295-6ada0fc859ef"
   }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "event_name:START AND session_id:${session_id}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Average bitrate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "alias": "Bitrate",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "data.bitrate", "id": "1", "type": "avg" }
     ],
     "query": "(NOT event_name:START) AND session_id:${session_id}",
     "timeField": "@timestamp"
    },
    {
     "alias": "Bandwidth",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "data.bandwidth", "id": "1", "type": "avg" }
     ],
     "query": "NOT event_name:START AND session_id:${session_id}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Last Metrics",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "NOT event_name:START AND NOT event_name:ERROR AND session_id:${session_id}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Load Time",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "event_name:START AND session_id:${session_id}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Event timeline",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 8 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "session_id:${session_id}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "event_name:ERROR AND session_id:${session_id}",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}