{
 "title": "Active Sessions",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Active Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Lates Errors",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "event_name:ERROR",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last Metrics",
     "type": "stat",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "NOT event_name:START AND NOT event_name:ERROR",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Load Time",
     "type": "stat",
     "gridPos": { "h": 11, "w": 6, "x": 6, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "event_name:START",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Average bitrate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "alias": "Bitrate",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "data.bitrate", "id": "1", "type": "avg" }
       ],
       "query": "(NOT event_name:START)",
       "timeField": "@timestamp"
      },
      {
       "alias": "Bandwidth",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "data.bandwidth", "id": "1", "type": "avg" }
       ],
       "query": "NOT event_name:START",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Event timeline",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}