apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -c -o helm-chart
    kompose.service.type: ClusterIp
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: elastic
  name: elastic
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elastic
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -c -o helm-chart
        kompose.service.type: ClusterIp
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: elastic
    spec:
      containers:
        - image: jspboix/elasticsearch:1.0.0
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: elastic
          ports:
            - containerPort: 9200
              protocol: TCP
            - containerPort: 9300
              protocol: TCP
          resources:
            limits:
              memory: "1073741824"
            requests:
              memory: "536870912"
      restartPolicy: Always
