apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -c -o helm-chart
    kompose.service.type: NodePort
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grafana
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -c -o helm-chart
        kompose.service.type: NodePort
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: grafana
    spec:
      containers:
        - image: jspboix/grafana:1.0.0
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: grafana
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
