apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -c -o helm-chart
    kompose.service.type: NodePort
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: qos-rest-api
  name: qos-rest-api
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: qos-rest-api
  type: NodePort
