apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -c -o helm-chart
    kompose.service.type: NodePort
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: qos-sse-broker
  name: qos-sse-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: qos-sse-broker
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -c -o helm-chart
        kompose.service.type: NodePort
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: qos-sse-broker
    spec:
      containers:
        - env:
            - name: PORT
              value: "8080"
          image: jspboix/qos-sse-broker:1.0.0
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: qos-sse-broker
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
