apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -c -o helm-chart
    kompose.service.type: NodePort
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: qos-data-transfer
  name: qos-data-transfer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: qos-data-transfer
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -c -o helm-chart
        kompose.service.type: NodePort
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: qos-data-transfer
    spec:
      containers:
        - env:
            - name: PILLARBOX_QOS_SSE_URI
              value: http://qos-sse-broker:8080/events
            - name: SPRING_ELASTICSEARCH_URIS
              value: http://elastic:9200
          image: jspboix/qos-data-transfer:1.0.0
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: qos-data-transfer
          ports:
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always
