apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -c -o helm-chart
    kompose.service.type: NodePort
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: qos-data-transfer
  name: qos-data-transfer
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    io.kompose.service: qos-data-transfer
  type: NodePort
