name: CI for Docker Compose

on:
  merge_group:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run services
        run: |
          docker-compose up -d --build
          docker-compose ps

      - name: Tear down
        run: docker-compose down
